---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      day: friday
    ignore:
      - dependency-name: "org.apache.tomcat.embed:*"
        versions: [ ">= 11.0.0" ]
